### ISSUE TITLE
Cryptocat takes hours to generate keys and fails to do so

### ISSUE THREAD

**Issue by jhzkongo** [cryptocat/cryptocat-ios#68]
I have not had trouble generating keys on my system, i.e. for gpg.
However, Cryptocat announces it is generating keys, then continues to do so for hours while displaying (interesting, at first) messages about cats.
Since there are no settings to tweak, I'm wondering what can be done about this.
Is there a way at least to troubleshoot what is happening?

**Comment by tbalthazar** [comment]
Looks like it is related to the Cryptocat browser extension, not the iOS app right?

**Comment by jhzkongo** [comment]
Yes 

James H. Zimmerman, Jr. 
Country Specialist, China 
Amnesty International USA 
PGP 96EC50A8
Phone 619.358.5965 sip:jhzkongo@ekiga.net 

     On Tuesday, January 13, 2015 12:15 PM, Thomas Balthazar <notifications@github.com> wrote:
   

 Closed #68.—
